..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r10 algae.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r10 dragon.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l10 -r4 gosper.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r6 hilbert.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r2 islandsAndLakes.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r3 kochIsland.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l6 -r4 kochTri.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l15 -r5 penrose.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l2 -r5 plant_a.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r5 plant_b.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r4 plant_c.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l2 -r7 plant_d.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l2 -r7 plant_e.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r5 plant_f.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l5 -r6 sierpinski.ls
..\bin\RubberPlant.App\Release\RubberPlant.App.exe -l6 -r5 stochastic.ls
